[package]
name = "armpi-tweaker-lcce"
version = "0.1.0"
edition = "2021"
description = "Arm-Pi Tweaker: Live Custom Creation Edition - Install and customize Orange Pi 5 Plus systems"
authors = ["Arm-Pi Tweaker Team"]
license = "MIT"

[dependencies]
slint = "1.3"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
log = "0.4"
env_logger = "0.10"
dirs = "5.0"
uuid = { version = "1.0", features = ["v4"] }
num_cpus = "1.0"

[build-dependencies]
slint-build = "1.3"

[[bin]]
name = "lcce"
path = "src/main.rs"

[features]
default = []
debug = []